name: deploy backend

on:
  push:
    branches:
      - main
 
jobs:

 
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/TodoProject/backend
            git config --global --add safe.directory /var/www/html/TodoProject/backend
            sudo git add .
            sudo git commit -m "serversidechanges"
            sudo git pull origin main
            sudo npm i
            pm2 ls
            pm2 restart 0
